# Generated by Django 4.0.4 on 2022-05-02 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vee', '0002_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
