# Generated by Django 4.0.4 on 2022-05-24 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vee', '0005_rename_wallat_userwallet_wallet'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=500, null=True)),
                ('txn', models.CharField(max_length=500, null=True)),
                ('method', models.CharField(max_length=500, null=True)),
                ('time', models.CharField(max_length=500, null=True)),
                ('from_ac', models.CharField(max_length=500, null=True)),
                ('to_ac', models.CharField(max_length=500, null=True)),
                ('vee_amount', models.IntegerField(default=0, null=True)),
            ],
        ),
    ]
